baseurl = "https://www.benovermyer.com/"
languageCode = "en-us"
theme = "manatrance"
title = "Ben Overmyer"

[params]
  author = "Ben Overmyer"
  description = "DevOps Engineer and Game Author"
  twitter_name = "bovermyer"
  sidebarrecentlimit = 7
