baseurl = "http://benovermyer.com/"
languageCode = "en-us"
title = "Ben Overmyer"

[params]
  author = "Ben Overmyer"
  description = "DevOps Practitioner, Self-Improvement Nut, and Fantasy Gaming Author"
  twitter_name = "bovermyer"
