baseurl = "https://benovermyer.com/"
languageCode = "en-us"
theme = "manatrance"
title = "Ben Overmyer"

[params]
  author = "Ben Overmyer"
  description = "DevOps Engineer and Fantasy Gaming Author"
  twitter_name = "bovermyer"
