[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.17.2"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = 0
    Content-Security-Policy = "style-src 'unsafe-hashes'; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'self';"
