[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.13.0"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = 0
    Content-Security-Policy = "default-src 'self' benovermyer.com *.benovermyer.com"
